spring.application.name=user_auth_svc


spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=039f74975f5d6d692b7ab72ccc8798aedf436d25a2dcf3f9cbf3da246d22ae33
jwt.expiration=86400000

logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %class{36} - %X{uuId}%X{txnId} - %M:%L - %msg%n
